# Copyright 2022 Cognite AS

## Import the Libraries and Modules

In [ ]:
import sys
from pathlib import Path

utils = str(Path("../utils").resolve())
if utils not in sys.path:
    sys.path.append(utils)

## fetching the function from the utils folder
from cognite_auth import interactive_client

# Create the Cognite Client

In [ ]:
client = interactive_client()

## List operation

**Code Pattern**
`client.<cdf_resource_type>.list()`
where **cdf_resource_type** = { data_sets, assets, time_series, events, files, labels, sequences, relationships ... }

### List the CDF Resource types

## listing data sets

In [10]:
client.data_sets.list()

DataSetList([<cognite.client.data_classes.data_sets.DataSet at 0x2251ac62800>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251ac62a70>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251ac63d30>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251ac639a0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251ac637f0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251ac63f10>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251ac63dc0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251ac63a90>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251ac63e20>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251ac63d90>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251ac638b0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251ac63b50>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251ac63b80>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251ac63970>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251ac639d0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251ac63a00>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251ac63be0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251ac63670>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251ac63f40>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251ac63ca0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251ac63eb0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251ac63cd0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251ac63e50>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251ac63a60>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251ac63af0>])

## Listing Assets

In [15]:
client.assets.list(limit=5)

AssetList([<cognite.client.data_classes.assets.Asset at 0x2251b0b7df0>,
           <cognite.client.data_classes.assets.Asset at 0x2251b0b7dc0>,
           <cognite.client.data_classes.assets.Asset at 0x2251b0b7730>,
           <cognite.client.data_classes.assets.Asset at 0x2251b0b7bb0>,
           <cognite.client.data_classes.assets.Asset at 0x2251b0b7a00>])

## Listing time series in a dataframe

In [16]:
df = client.time_series.list(limit=None).to_pandas()
df

,name,is_string,metadata,asset_id,is_step,security_categories,data_set_id,id,created_time,last_updated_time,external_id,description,unit
0,Burundi_population,False,{},5697153113883451,False,[],2276878852808414,1331069082036,2025-06-17 12:04:40.159,2025-06-17 12:04:40.159,NaN,NaN,NaN
1,Serbia_population,False,{},6614586751832789,False,[],2276878852808414,3234769100235,2025-06-17 12:04:40.159,2025-06-17 12:04:40.159,NaN,NaN,NaN
2,Egypt_population,False,{},1769928733859550,False,[],2188261475079071,5574976906097,2025-06-13 08:12:16.531,2025-06-13 08:12:16.531,NaN,NaN,NaN
3,Belize_population,False,{},5301566077404501,False,[],7072143181146579,8403038180819,2025-06-16 20:29:22.748,2025-06-16 20:29:22.748,NaN,NaN,NaN
4,Guinea_population,False,{},1219829490273030,False,[],9000161995369545,11806354552773,2025-06-22 08:54:31.222,2025-06-22 08:54:31.222,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2881,Costa Rica_population,False,{},8242863335066523,False,[],8328588184637507,8998287234547349,2025-06-11 04:31:10.416,2025-06-11 04:31:10.416,NaN,NaN,NaN
2882,Turks and Caicos Islands_population,False,{},323132027850373,False,[],8328588184637507,8999046453019951,2025-06-11 04:31:10.416,2025-06-11 04:31:10.416,NaN,NaN,NaN
2883,Equatorial Guinea_population,False,{},253130292104170,False,[],8338308414184835,9001359458118332,2025-06-23 18:51:26.043,2025-06-23 18:51:26.043,NaN,NaN,NaN
2884,Israel_population,False,{},8784594044911916,False,[],7373915476976698,9001756329253678,2025-06-17 15:01:56.185,2025-06-17 15:01:56.185,NaN,NaN,NaN
2885,Gabon_population,False,{},7012127829591313,False,[],7373915476976698,9004231431144209,2025-06-17 15:01:56.185,2025-06-17 15:01:56.185,NaN,NaN,NaN

In [17]:
df.shape

(2886, 13)

## Listing Events

In [18]:
client.events.list(limit=5)

EventList([<cognite.client.data_classes.events.Event at 0x2251b3738b0>,
           <cognite.client.data_classes.events.Event at 0x2251b372440>,
           <cognite.client.data_classes.events.Event at 0x2251b3738e0>,
           <cognite.client.data_classes.events.Event at 0x2251b3739a0>,
           <cognite.client.data_classes.events.Event at 0x2251b3716c0>])

## Listing Files

In [19]:
client.files.list(limit=5)

FileMetadataList([<cognite.client.data_classes.files.FileMetadata at 0x2251b3727a0>,
                  <cognite.client.data_classes.files.FileMetadata at 0x2251b373be0>,
                  <cognite.client.data_classes.files.FileMetadata at 0x2251b372470>,
                  <cognite.client.data_classes.files.FileMetadata at 0x2251b372350>,
                  <cognite.client.data_classes.files.FileMetadata at 0x2251b3734f0>])

## Similar code for listing other resource types


```
client.labels.list()
```
```
client.sequences.list()   --> sequences are the resources which do not have a time series index, like performance curves etc.
```
```
client.relationships.list()
```

In [20]:
client.labels.list(limit=5)

LabelDefinitionList([<cognite.client.data_classes.labels.LabelDefinition at 0x2251b372740>,
                     <cognite.client.data_classes.labels.LabelDefinition at 0x2251b3708b0>])

In [21]:
client.sequences.list(limit=5)

SequenceList([<cognite.client.data_classes.sequences.Sequence at 0x2251b372590>,
              <cognite.client.data_classes.sequences.Sequence at 0x2251b372530>,
              <cognite.client.data_classes.sequences.Sequence at 0x2251b3733a0>,
              <cognite.client.data_classes.sequences.Sequence at 0x2251b373220>,
              <cognite.client.data_classes.sequences.Sequence at 0x2251b3732b0>])

In [22]:
client.relationships.list(limit=5)

RelationshipList([<cognite.client.data_classes.relationships.Relationship at 0x2251b373c70>,
                  <cognite.client.data_classes.relationships.Relationship at 0x2251b372920>,
                  <cognite.client.data_classes.relationships.Relationship at 0x2251b3736d0>,
                  <cognite.client.data_classes.relationships.Relationship at 0x2251b371ea0>,
                  <cognite.client.data_classes.relationships.Relationship at 0x2251b372d70>])

## Filter the list results
    - Using label filter, the data in cdf doesn't have these labels. But it is an example on how to filter with labels

### importing the LabelFilter class from data_classes

In [23]:
from cognite.client.data_classes import LabelFilter

In [24]:
client.assets.list(labels=LabelFilter(contains_all=["industrial-assets"]),limit=5)

AssetList([<cognite.client.data_classes.assets.Asset at 0x2251b371660>,
           <cognite.client.data_classes.assets.Asset at 0x2251b373100>,
           <cognite.client.data_classes.assets.Asset at 0x2251b371960>,
           <cognite.client.data_classes.assets.Asset at 0x2251b372200>,
           <cognite.client.data_classes.assets.Asset at 0x2251b372800>])

In [25]:
client.assets.list(labels=LabelFilter(contains_any=["industrial-assets"]))

AssetList([<cognite.client.data_classes.assets.Asset at 0x2251b370970>,
           <cognite.client.data_classes.assets.Asset at 0x2251b371bd0>,
           <cognite.client.data_classes.assets.Asset at 0x2251b370520>,
           <cognite.client.data_classes.assets.Asset at 0x2251b370760>,
           <cognite.client.data_classes.assets.Asset at 0x2251b370400>,
           <cognite.client.data_classes.assets.Asset at 0x2251b3705e0>,
           <cognite.client.data_classes.assets.Asset at 0x2251b3722c0>,
           <cognite.client.data_classes.assets.Asset at 0x2251b3702e0>,
           <cognite.client.data_classes.assets.Asset at 0x2251b370820>,
           <cognite.client.data_classes.assets.Asset at 0x2251b370370>,
           <cognite.client.data_classes.assets.Asset at 0x2251b3720e0>,
           <cognite.client.data_classes.assets.Asset at 0x2251b3714e0>,
           <cognite.client.data_classes.assets.Asset at 0x2251b371fc0>,
           <cognite.client.data_classes.assets.Asset at 0x2251b371c90>,
           <cognite.client.data_classes.assets.Asset at 0x2251b3704f0>,
           <cognite.client.data_classes.assets.Asset at 0x2251b370700>,
           <cognite.client.data_classes.assets.Asset at 0x2251b3708e0>,
           <cognite.client.data_classes.assets.Asset at 0x2251b370a30>,
           <cognite.client.data_classes.assets.Asset at 0x2251b370af0>,
           <cognite.client.data_classes.assets.Asset at 0x2251b370c10>,
           <cognite.client.data_classes.assets.Asset at 0x2251b370ca0>,
           <cognite.client.data_classes.assets.Asset at 0x2251b370b50>,
           <cognite.client.data_classes.assets.Asset at 0x2251b370d60>,
           <cognite.client.data_classes.assets.Asset at 0x2251b370f10>,
           <cognite.client.data_classes.assets.Asset at 0x2251b370fa0>])

# Other filters

In [26]:
client.data_sets.list()

DataSetList([<cognite.client.data_classes.data_sets.DataSet at 0x2251b3715a0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251b372170>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251b372dd0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251b373c40>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251b372770>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251b373b80>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251b3725f0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251b371e70>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251b3728f0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251b373d30>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251b3730a0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251b373460>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251b373a00>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251b371cf0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251b373ac0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251b373640>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251b3711b0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251b370670>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251b370790>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251b372980>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251b372fe0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251b372050>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251b370940>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251b371540>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251b3718d0>])

In [27]:
client.data_sets.list(write_protected=True)

DataSetList([<cognite.client.data_classes.data_sets.DataSet at 0x2251b3703a0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251b3722f0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251b3719c0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251b3715d0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251b372320>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251b373400>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251b371270>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251b373b20>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251b372a40>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251b3728c0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251b371840>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251b371240>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251b371360>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251b372ad0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251b371450>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251b371b70>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251b373ca0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251b372020>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251b370610>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251b3716f0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251b373430>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251b372f80>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251b370250>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251b3735b0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251b371420>])

In [28]:
client.assets.list(root=True)

AssetList([<cognite.client.data_classes.assets.Asset at 0x2251b371cc0>,
           <cognite.client.data_classes.assets.Asset at 0x2251b372e00>,
           <cognite.client.data_classes.assets.Asset at 0x2251b08f220>,
           <cognite.client.data_classes.assets.Asset at 0x2251b08ec50>,
           <cognite.client.data_classes.assets.Asset at 0x2251b08e800>,
           <cognite.client.data_classes.assets.Asset at 0x2251b03d5d0>,
           <cognite.client.data_classes.assets.Asset at 0x2251b03db40>,
           <cognite.client.data_classes.assets.Asset at 0x2251b03c910>,
           <cognite.client.data_classes.assets.Asset at 0x2251b03e9b0>,
           <cognite.client.data_classes.assets.Asset at 0x2251b03fb20>,
           <cognite.client.data_classes.assets.Asset at 0x2251b03d450>,
           <cognite.client.data_classes.assets.Asset at 0x2251b03e170>,
           <cognite.client.data_classes.assets.Asset at 0x2251b03ee30>,
           <cognite.client.data_classes.assets.Asset at 0x2251b03cc40>,
           <cognite.client.data_classes.assets.Asset at 0x2251b03e860>,
           <cognite.client.data_classes.assets.Asset at 0x2251b03cee0>,
           <cognite.client.data_classes.assets.Asset at 0x2251b03f910>,
           <cognite.client.data_classes.assets.Asset at 0x2251b03fd00>,
           <cognite.client.data_classes.assets.Asset at 0x2251b03ff70>,
           <cognite.client.data_classes.assets.Asset at 0x2251b056d40>,
           <cognite.client.data_classes.assets.Asset at 0x2251b057340>,
           <cognite.client.data_classes.assets.Asset at 0x2251b055000>,
           <cognite.client.data_classes.assets.Asset at 0x2251b056bf0>,
           <cognite.client.data_classes.assets.Asset at 0x2251b0561d0>,
           <cognite.client.data_classes.assets.Asset at 0x2251b057580>])

# Iterate over the list

In [29]:
for data_set in client.data_sets:
    print(data_set.id) # do something with the data_set

532492593814
3708248994472
8971087276716
14634448291637
22547179591127
23758930699440
32889565298826
39210236434027
40327729659769
48758153143218
49161542373901
53733012649311
58158657947049
58839366849857
74431833051045
77646949468688
85963087988610
86545673296094
88809449333750
91028975699979
99825339813632
104573554199652
106313613626018
111662049520578
132053933855106
140804500368758
143222670456404
145208858652069
146987707262722
168085293540831
169685299373191
179556465647798
197929698661134
198122773158762
199327379323816
206245056521975
207573897183612
215787008330337
216292905815470
235504890779413
245211532024983
246644328516666
248638948877491
252666839699577
257089475305167
262253023676364
265431403968007
269244871670358
270019166497168
270478968056738
276165573849325
279042604876042
280384459601303
282044034755572
285082936999171
286953708826887
300212271108879
302428767654888
304901974689240
314274225507819
319694119277473
321926613231193
322621260179540
327168443834829
328580403083325
329072658213138
332047216091763
334893065260762
339913999390152
342164539129005
343884367520567
351455938750371
351677402697202
351737611876309
353712872146981
356556244549877
360770756365631
361044291120590
361983842667871
366735187905526
367655503293353
371471186486047
371567262787826
373080082861177
374204154593058
382894356027718
383066267796045
383753923143873
384544486547812
384624714752900
385972676194758
386353505713897
390179783824555
391414095118278
401125870582609
404471063348808
406431760122242
413061222491199
413965148048302
415288079495233
424289964247328
427431636839196
429165497317995
432685068344160
433036204648308
433265370909592
434019636830057
443116462040741
446762918876037
448190392315812
449268054362853
449548606820413
462194125035131
463575659130775
465766172081624
470668994903462
473816852723090
475478346606191
477069656330748
479684261347340
479858170499604
490409063677896
490550367174858
494287051929265
495539672222658
496051429731132
496886847982129
501020884164814
502170041871567
513185859774038
522304100048078
524283069591365
528566429918169
528621123672780
533353862940890
533450796260544
544137566156262
546967672490966
549213080710281
559502720486651
562145541113805
562734322327098
564835584293954
567191607921657
570085452651205
575201612783267
580309958313586
581316889469386
584163244948373
596198678921811
599553620410680
604961095741056
606404139885877
609556684295853
617876033049454
618536257256689
619824695038924
621183638086794
621288550636820
622035521948167
622654156128468
626797002324442
628533913420862
631718099623657
633834219402392
638887774192041
639648821583111
641983919446570
643872147234439
644580965252057
646997894298288
648458141283169
648983665321516
652544550111155
655334118870390
664327536309723
667849636971004
692953582196731
698456253899276
703084601901793
707004358407472
708537326924316
710802418669543
713130601702471
716976346814951
723591686585852
725966825136179
727544688426623
738184721860467
741555973457573
746472989768288
748616310034138
754258185128677
771376250286324
771851152075112
781279975903043
793383259540440
793469941497350
795659557428953
798497403683373
804133470587960
804225262817351
804245936865363
805708359016417
807824827711867
809866718134772
812076573357531
817097687377880
817114135115991
820355579308931
821729274408808
823161786853523
826761420013544
829587244760337
830129380974040
830381672316401
831254441409725
838086826086989
840629724410194
842419528435765
848276701963218
853154154335514
862664667214331
865832119584036
868380830013266
869475774773744
874868730032339
875175570263312
881996471867649
883818066079078
888027364703447
889452778498716
890152991890022
906242300278302
911216358192603
918592566336184
920221886368799
922201656914718
925346514448821
941938870420442
944310560620034
945879140892084
948017290428938
950745464373043
952090479554162
954928425324575
960250379695725
961946951876136
962357111547552
968286623270884
968707581577342
974658736134817
984649657843219
988086870624681
994387249581637
999303290864023
1003672976961003
1006272666556849
1008474567305486
1029164115014335
1031269583017441
1033956203226101
1042128879577905
1046638494626679
1049587459488521
1051968615496607
1055890999245178
1059268772539258
1062225714431722
1069078470081562
1069108139629359
1069554777427556
1073941803295323
1077311824730644
1077532010327178
1085289270190123
1086518905429005
1088213358773824
1103888029851747
1107177383117395
1113029714013594
1116672108994183
1119479084535104
1128874287043623
1130451088557745
1136283601500279
1139000062711017
1141373574368248
1150408489563842
1151387135776235
1158191685524419
1158245760718226
1162597637831191
1163723778772280
1170131357124402
1177098242095797
1178181417390995
1179901601543761
1182254724540116
1185369701040814
1185379204284366
1190907308918163
1199717751344391
1201724655593148
1202614998030699
1204659439623409
1205762913409378
1207419306061403
1214649783362589
1216258026128952
1217495954051771
1221857277384525
1225524975600227
1227181740137519
1229896871721511
1234423956697155
1241330167565866
1250270226890324
1251272489873371
1251893447603416
1257048453657126
1257443571509816
1257704953866882
1261168789199063
1261797372068912
1275915436327503
1280765655926353
1282062143478093
1282458501305523
1282898300177116
1288446642529445
1292072704503015
1297667605274801
1298813387174538
1304090583104182
1306101474874408
1310301878819043
1311557794448791
1316852108822915
1322039641564162
1322507546937155
1325366888564171
1325550905109754
1327845013204933
1334403970201787
1335974605383758
1339167715961126
1343517314257611
1345141187162439
1348843871235415
1354441314762354
1360743317559049
1360916600003284
1365206592161207
1366801261827676
1371996313381598
1377173340715899
1377618256482266
1379285418425613
1390897584998145
1395837932266356
1399248851345249
1405078456049484
1407152301190633
1408826934075429
1410441463659350
1410817623288435
1416144622016281
1417504489694440
1437069057888090
1442666494246490
1444875267593700
1447039128481344
1450105305868620
1460997700539257
1473681769768562
1476863929372273
1479695427068553
1479859102324048
1481223137220244
1487269770110667
1488795879919094
1489815605202942
1489902570422214
1493773091431978
1494962522520179
1497348963839079
1498932839973608
1502893976524035
1506031672164449
1507415726010715
1508853694935928
1510149271404841
1516463030274855
1518216444980401
1523787130682392
1524680983700698
1526456776531167
1532027212687982
1532710302243912
1532766366247234
1532979745978890
1536466979139369
1537272020415973
1539366795838152
1541809918869683
1543513110408351
1543671114961434
1543802470619707
1546930207807636
1547476927628082
1551836458301371
1552051149042891
1561563571153069
1566912988358750
1582143962523171
1584956118559415
1587961605158576
1588429512031562
1592832778753807
1592917301408796
1593428488435041
1599807693367908
1601839921145602
1604114553000868
1605844253137626
1614986846616846
1615371704518171
1620689599109719
1621973293707004
1627326272447682
1630873497711015
1631760662759693
1639352588235575
1641607801569174
1653105143684388
1655831984591737
1655953644751336
1656307260690554
1660720134422832
1667937939869668
1674049361118152
1682081983385086
1693929257222548
1698338843871346
1701895473801216
1702154281334276
1706434942098141
1707976748808707
1712580253673439
1717506819349544
1720743512081697
1720753366928347
1721856088577685
1724133522394150
1728216045075991
1732294606267560
1732727878938189
1737457001048699
1738519957792732
1740780225682649
1747856776032809
1748345613069565
1749194870861860
1750274230457497
1751446784428404
1752864791548892
1753213973038658
1753859835900799
1757108344638665
1758068328366388
1781014955065063
1787073774378916
1789173885320064
1790253453828748
1794370249726288
1803290549349038
1803574737380074
1808390802134893
1809543230872644
1813555308922183
1817292694398048
1819612230300151
1828067098665441
1828703952665519
1830519700145818
1833453309074835
1839945049570897
1843379459643733
1857079057906957
1861958158148276
1863770681242809
1864623766192844
1864635290563035
1870565208541223
1884540635691659
1886546571747999
1888547541855520
1895449624133541
1900770456801810
1906350907966575
1907752641369576
1908741361361709
1910970948827912
1913038613496780
1919540092209414
1929610961715132
1931626738612293
1934685661543316
1936627898746789
1942362572002902
1946995391869517
1952282575470510
1952587161485482
1954747345924765
1959968568110613
1960306834826964
1963068089734413
1963187760514670
1967975012488138
1975427709700793
1979885435250559
1987474413936898
1988807819931114
1989032900602918
1990351901786303
1992495024863616
1999140268933734
2000381036676167
2001779596692798
2003426439066220
2004275097557060
2006874460682820
2007475723851843
2010926689828620
2011779359651204
2013322688485496
2017871029095129
2022625971638744
2026721352316346
2032957843429776
2036480507542760
2037195965478868
2038884433454456
2039353330061288
2041823343172129
2048449721536080
2049448152475997
2053631970639347
2054663369052065
2054820104584595
2055148352894156
2055427241683204
2067438104175391
2070377851473516
2076049946223270
2076371233174065
2080214821397583
2081033156072552
2084872831251333
2086618822392102
2087013198427290
2087707021674810
2087890923208881
2097849914635830
2100806649564178
2100865133097895
2105816208354166
2107133669343331
2110511728198653
2112085192609282
2120275915768684
2121229839567051
2125146344761050
2130912180259306
2136524331258196
2145427014541445
2146641098675213
2154946647964581
2155653646196720
2157837334446681
2158198703770447
2158223360516096
2158417735537758
2165836082097760
2165969613254318
2166061438529203
2168263397591759
2170294417906859
2175152792732886
2183554967062468
2188261475079071
2190765946098446
2193341054168870
2199269918525463
2202053283896355
2211896621442173
2213346138706201
2214459252214907
2216345027946073
2219971054379027
2228561134884327
2229431337011466
2234916403658822
2238694842784134
2242860718287646
2246995365388771
2247282766885987
2251923110868351
2253536859693461
2267991068273859
2268594678044122
2269739118258664
2270685781082179
2274224619096450
2274437332715013
2276878852808414
2278720343066350
2278860425327819
2283038941199500
2288702427156613
2294035991131906
2297036148906945
2298783446247822
2302574189838796
2304188028315611
2312404640641680
2314347103024143
2316989702069396
2321470076939145
2323388896486300
2324792428591641
2328424159296909
2328874100370204
2329898891769772
2332176518181668
2342711677808663
2343275210198625
2348496359891873
2362826850895131
2365041167097284
2367684652022147
2372322479882281
2378160226478316
2386537515057657
2387444884144279
2388878271722297
2396284437442394
2400267457774931
2402129104213694
2404911254114854
2405246425701403
2407169140096262
2416264946706357
2419060250033884
2431053139606395
2433705488986472
2437010206622903
2443650227116126
2448797374410520
2455963958369937
2459991516258283
2461063811878702
2468542287064164
2471274175128842
2477315746812839
2479226484426115
2479632565248609
2482348096223051
2482878848529752
2486254797063309
2487875745344080
2490833447988795
2503748567311116
2504349779542087
2506556781328576
2508161350337467
2511410068159976
2514232821858109
2515479368700393
2518420846775699
2523195970186524
2528082388020962
2528428316884654
2528911606274376
2530792656534022
2532666240556727
2534436513838083
2539547555786952
2541855942625840
2542748006079220
2549777223194629
2553579104506664
2562291634391494
2566206333470905
2566919603643804
2567011028662956
2569399397330280
2570325016218389
2577408094335289
2584735913388066
2585807599522491
2597143405113932
2603356844421037
2606186489548451
2608638426110344
2634887179173885
2638270174594285
2643068784551291
2648803228150271
2653857466275743
2660967612150257
2669928268835509
2671128214328004
2677769742989193
2681135282752042
2681998300430763
2683840985568138
2684762043942063
2686406063087083
2687480192676654
2690506626357359
2697380900418431
2697647321085456
2699179676442792
2700676249981809
2701219236708955
2706913852840580
2707004872677087
2712527563164807
2714360670642521
2715648553624699
2717370297480209
2723280590887824
2730151622033299
2736472442884836
2739378655952392
2740666164876775
2745766591440228
2748583307904895
2750367382323356
2755684955624724
2758270384847173
2761019829124598
2762911056966549
2764923743457275
2766515671855029
2766895056462183
2767068002060556
2772693738155375
2773404321714470
2774346283212177
2777023782445364
2779298869985864
2782365176345025
2789769386171434
2791022208205594
2802639225490455
2802892716241974
2808682157342157
2810267761982962
2814075393904743
2814308704490141
2817722876339519
2823096012388271
2829041337204995
2829255563463317
2829507119800183
2829967311007856
2830841203522276
2832194960304291
2832798507032545
2835391039399971
2843080094497016
2844239600192708
2844420040823851
2848262606907397
2863083222824019
2864028039322318
2864084667188549
2865315723998713
2866588920299148
2877716469277629
2878151803791487
2878601329585964
2883022880948923
2888899222977130
2890751634110183
2894001993986892
2909088323190810
2910359974429237
2910874487472253
2911256178469946
2911661927586981
2915632814076591
2919914891654291
2920736797545728
2920878072079918
2921423200866915
2922185029699191
2923518586671451
2926170034395795
2928085124529513
2938770007994363
2943365034383957
2944115116154600
2947927670268479
2949483618812864
2959128939610251
2960291722519684
2961132027173142
2965083518868723
2967131971888708
2968452334072263
2971522514911109
2971637976007819
2975049978386645
2981188893992453
2981567217401545
2987360961444415
2994299659869265
3002338033726407
3009107085786448
3019323552983707
3026346476590298
3029362296298137
3029855342081328
3041437975324122
3045568420517075
3050343233034734
3063556664814733
3071051556540113
3073360283621350
3080098747541952
3090175246942918
3092041450978691
3093417845259064
3097799896300265
3099547207394818
3101980504590162
3102094802056404
3109354098195961
3110028246027577
3114562492264894
3120945599259676
3123288396438708
3128575396904089
3128701522386857
3131899688655091
3140729701001983
3143971860614624
3144031455705029
3150157819272614
3164107093335332
3165249129478603
3169594204643666
3170354942225016
3171288875389964
3171366310320678
3172184117846700
3179270895544398
3180131923927704
3186736809549537
3193076875681489
3206977470130206
3210578534301829
3221694486809650
3222969181814429
3224972408618222
3225982717615525
3227705308010108
3230714509134473
3231699189902647
3234183566463212
3235449573581295
3238229103456500
3244712267049468
3247452778441480
3250883404167972
3252863470388905
3261236690954880
3262481510309580
3264944581136027
3265443361732514
3266147401380228
3280574413693342
3287820411765745
3287870284937685
3288322934837091
3297194535279959
3298380217362572
3298935352970736
3299453579048689
3301955055471451
3302304397764914
3304505676642078
3312479120938167
3317891590714558
3321183524172910
3333812893008964
3335318105159292
3338733773633920
3343597430003257
3352632773291711
3355731989695589
3358729745226450
3367713126145156
3368330750859886
3370129852713206
3378767309410957
3381409674111087
3382913029471631
3388221673305633
3389301527726743
3390632273018963
3391104403306813
3393601245516851
3394693288431357
3397248522627607
3402534891148056
3404629494770529
3408048953811709
3416167160753839
3428499361999735
3436864625169384
3444323436250800
3454682137601544
3457368556271423
3462143781298735
3462310269585919
3470052309427755
3475301909718213
3486064982377811
3493683289413862
3500061215272723
3507031004300529
3510788110014927
3511163603305418
3514274326291052
3515245018468204
3519200573780803
3529110873538820
3529302691607226
3537344943069726
3543743391411107
3543993073242866
3554263512677325
3556565438145060
3563377918065274
3565213266965394
3565337827844169
3568039434723949
3574660335548088
3578964755308630
3578991042976025
3579784173150635
3579934415299374
3589217527491953
3592798698384988
3594072405435655
3601641288743290
3605750943514445
3608455444535346
3608615516230687
3610024291650900
3610074902696354
3614161966590652
3625288193520803
3640758827042012
3641331840264683
3641617916302981
3645441687189834
3651001084031369
3652367606521912
3655246966153056
3655333560465258
3662542168526863
3664424586466493
3669200684280916
3672457915988343
3682427831848495
3684230470887241
3685752564837946
3696121708027350
3697778639944040
3703710687922399
3710718861230855
3711240786717478
3713911304657310
3718800626055985
3721182921446592
3722275870884225
3722751284432185
3726382651228220
3733968516019731
3740096947506843
3740111082469728
3745648415825307
3749113810669735
3749122422937367
3750840315198849
3751120141375545
3751875097267449
3759263795744920
3765682391452196
3765902310798570
3767620890129400
3773978879153155
3777322656773166
3778796547548500
3783746997545497
3788520542476349
3790481727039981
3792378464081891
3794563852459650
3800498821188785
3800911452820180
3805704781905558
3815242376959400
3815514760449738
3816335283218153
3824614335734696
3828153965543112
3830681777151080
3831706406390209
3832321040888193
3835314484833739
3836955444662784
3848124341002420
3849393743498442
3852184028961488
3860783980896816
3862381826615487
3864955317242534
3869527237329571
3872344724289623
3876540822480872
3877646162208394
3878639911984981
3884534200782092
3886318856603660
3906543285049665
3917702687898205
3920244778883779
3924304056401318
3928463193601741
3939502344192846
3943751568013551
3950596727332636
3950678655551597
3954427163642507
3954959707788761
3960208359913788
3960584930107313
3976107012307108
3977876033960662
3982295575048428
3985011131997081
3988379457964629
3989178566058017
3989459344158182
4004935783161542
4010941073966255
4014420929451670
4015074109035671
4020787981664457
4027063284701907
4030041932843866
4037933017324208
4038419109041753
4042944056718239
4053323913684000
4053378846633659
4057294432221931
4059991665993701
4064611348909151
4069217386658534
4085313629438009
4089554646832446
4102565334413619
4104686870127247
4106015515414417
4108718241711122
4108826492904666
4109764059855187
4118084374390093
4118219044676205
4118597891600061
4120250262454082
4123272018176181
4126713562813832
4130057822569445
4135702995092093
4135729107043139
4139182864858070
4140193104038026
4141799556825488
4143133271471457
4146395646688779
4147091756646984
4152874653848009
4158819849330865
4166063996359043
4166959852225399
4167273839244078
4168570311010678
4169411546175140
4171987262740887
4184380438509218
4185426435703370
4186039898432735
4190173354021414
4192476152221513
4197781512705091
4198465485109543
4203065344689810
4203967703520451
4207122715549721
4209824204794440
4214936602614572
4219295039266605
4228382033912024
4229268820820420
4233571227781494
4244444901198468
4244530626721045
4246909034825718
4248533333143857
4250004790588935
4250864005588055
4262209016570164
4266287005388355
4270422284255266
4273377082299023
4277967092030599
4279887180785779
4280910206734727
4282715273465147
4284056140548956
4286787021265040
4286836962388919
4290898735482195
4304481465774348
4307260100463641
4310732894240737
4313767068448871
4318079355011139
4318194516088622
4319392085402913
4319480107942438
4320139463675511
4325074729413480
4327586284635840
4331071906211675
4338250878599695
4339754203585974
4340348255324159
4340995703376020
4342099530489135
4349182572455794
4353792050693837
4360915987386966
4364000403696354
4367080077305747
4368108799918719
4369337212099050
4371798722812486
4374962094927501
4376664350048143
4376854949258633
4379626006943766
4397486057907956
4398088023276752
4401961752868171
4406628759478623
4419744397114747
4426597301787073
4430077514128268
4445044907858927
4446987946101068
4449498483741645
4452771281937029
4454816505788968
4464265759235881
4465916347287457
4468391887208184
4470810975598267
4483543895251647
4487345076882078
4488760112881998
4491172761130378
4494884813242363
4501800679948022

### When List is too big, then use the **chunk_size** parameter to get the list in chunks

In [30]:
for data_set_list in client.data_sets(chunk_size=5):
    print([x.name for x in data_set_list]) # do something with the list

['TestDataset_pawara', 'pawel_world_info', 'my_example_dataset', 'world_info_jack', 'aleksander_my_example_dataset']
['Marie_world_info', 'Crístian2_world_info', 'world_info_jack', 'world_info_jack_11', 'world_info_jack']
['world_info_jack', 'jdavid87_example_dataset', 'world_info_Timi', '1st level', 'my_name_example_dataset']
['my example', 'world_info_mohsen', 'world_info_bhaskar', 'kiyoshi_world_info', 'world_info_jack_SAYAN']
['patrick1998_world_info', 'test', 'Prince_example_dataset', '1st level K', 'world_info_jack']
['SofieHaug_example_dataset', 'Eduardo_example_dataset', 'jonathan_world_info', 'Srujana_world_info', 'my_example_dataset_wu']
['guilherme1990_exemple_create_python', 'ole_wammer_world_info2', 'smrsgv_info_jack', 'my_example_dataset_rodrigo', 'Test']
['my_example_dataset_temp', 'Ana2002NOR_TestDataset', 'third example', 'hanan_world_info', 'world_info_Pablo']
['Could anyone help remove this?', 'Fadi_example_dataset', 'GPaulo2000-IFSDB', '1stLevel', 'a_my_name_example_dataset']
['Vijaya New Dataset', 'Cornelius_world_info', 'gcbiotec_world_info', 'patrick1998_world_info', 'world_info_test_2']
['Ariel_HandsOn2_DataSet', 'world_info_jack', 'TestDataset', 'world_info_jack_sohaib', 'world_info_jack']
['Luiz’s Personal Time series', 'mp_two_dataset', 'Test set', 'raj_world_info', 'ruben1984_example_dataset']
['write-protected-data', 'joshan_world_info', '{my_name}_world_info_jack', 'my_dataset', 'Yazan_example_dataset']
[None, 'krishna2001-Aveva.Net', 'vetle_world_test', 'Isabela2001_example_dataset', 'world_info_shiva']
['world_info_beni', 'Alex_world_info', 'my example', 'ajha10_example_dataset', 'Shiva']
['TestNK', 'world_info_jack', 'Andreea_world_info', 'world_info_jack_novajj', 'world_info_andrew']
['Rafli_world_info', 'irma_test', 'world_info_wei2010', '1st level-gs', 'my_example_dataset']
['heydar_worl_info', 'my_example_dataset_www', 'Gayathri_world_info', 'world_info_jack', 'Mostafa_world_info']
['dil_world_info', 'Maciukas_example_dataset', 'Andreea_world_info', 'Shiva', 'Simone_world_info']
['test_dataset8', 'my_example_dataset_vgr', 'world_info_areisdorf2', 'Maciej_world_info', 'second example']
['saif_example_dataset', 'world_info_jack_as', 'world_info_sofie', 'gann2023-AvevaNet', 'Dzmitry1994_world_info']
['Vijaya_dataset', 'Tiago_world_info', 'camilla1996_world_info', 'Arpita2020-AvevaNet', 'PM_world_info']
['my_example_dataset23', 'world_info_krutip', 'mylittlepony_world_info', 'mylittlepony_world_info', 'Jorgen_world_info']
['blah_example_dataset', 'third example', 'world_info_chandc', 'world_info_jacksonG1994', 'my_example_dataset_006']
['hola', 'lsun_world_info', 'myworld_info_jack', 'DipeshYogi1994_world_info', 'MJ']
['faraz_alm', 'david_a_example_dataset', 'Trond_world_info', 'Rui77', 'Nick0000-IFSDB']
['second example', 'Naoki_example_dataset', 'world_info_jackcity', 'my_example_dataset', 'my_example_dataset_1']
['world_info_suplenteeee', 'Medryl_world_info', 'world_info_andrew', 'amitoj_world_info', 'rsk_ds1']
[None, 'world_info_jack', 'world_info_jack', 'world_info_jack_njj', 'world_info_ivar2']
['bojja_world_info', 'faisal_dataset', 'leandro1986_example_dataset', 'Mostafa_world_info', 'FirstnameBirthyear-AvevaNet']
['mfc', 'my_example_dataset_Him', 'Medryl_world_info', 'Dag1985_2_example_dataset', 'world_info_jack_suplente']
['Ivar1999_example_dataset', 'world_info_andrew', 'world_info_jack_Manv', 'rawan_world_info', 'Adriano2024_data_set']
['world_info_jack_99999999', None, 'world_data123', 'Rafli_world_info', 'christian_world_info']
['con_gtl_example_dataset', 'world_info_john', 'SIOD1980-AvevaNet', 'neil_example_dataset', 'Mudassir_world_info']
['gcbiotec_world_info1902A', 'mylittlepony_world_info', 'my_example_dataset_001', 'mohammed_al_safwan_example_dataset', 'world_info_adeeb']
['Medryl_world_info', 'my_example_dataset_test1', 'world_info_mugless', 'Medryl_world_info', 'Mat1989_dataset']
['Mostafa_TestDataset', 'TatVF_world_info', 'my_example_dataset', 'third example', 'test_world_info']
['faisal_dataset', 'Rajat1985-IFSDB', 'JorgenAa_world_info', 'my_example_dataset', 'muhammad_jb_world_info_example_dataset']
['lucas2000-ds', 'FirstnameBirthyear-AvevaNet', 'world_info_jack_mm', 'dalvania_world_info', 'newworld_info_jack']
['chand_world_info', 'Tetsu_example_dataset', 'world_info_jack', 'wu_world_info', 'world_data']
['Mudassir_world_info', 'neil_v_world_info2', 'Marcos81-6._world_info', 'sindre_world_info', 'dan_1979_example_dataset']
['2nd level', 'world_info_timo', 'teodor_world_info', '2nd level', 'juan_world_info']
['Ruslan_world_info', 'world_info_Kush', 'emmab_world_info', 'world_info_jack', 'Juan Alvarado world info']
['world_info_academy2', 'pawel-test-dataset', 'second example', 'hmnasri-CDF3', 'world_info_andrew']
['smart-home-dataset', 'world_info_jack', 'angelica_world_info', 'saif_world_info', 'camilla1996_world_info']
['joshan_world_info', 'Crístian_world_info', 'poc_example_dataset', 'Elcio19620805hands-on_world_info', 'DeepEnd_world_info']
['kimsb_world_info', 'JorgenAa_world_info', 'Mohamed_example_dataset', 'caroline_f_world_info', 'my_example_datasetcas']
['vinicius_peres_world_info', 'world_info_kailash', 'second example', 'Simone_example_dataset', 'Mikalay1991:my_example_dataset']
['jeanarnaudritouret_example_dataset', 'heman_dataset', 'Elciocs1962hands-on_world_info', 'world_info_wwu_H2', 'frendi_world_info']
['Diana_world_info', 'world_info_1991_2', 'clement_world_info', 'john_world_info', 'world_info_jack']
['sharizan1981_dataset2', 'my_example_dataset_Long', 'Ariel_example_dataset', 'my_example_dataset', 'world_info_takei2']
['world_info_kruti', 'Simone_world_info', 'gayathri_world_info', 'juan_world_info', 'prefix']
['rsinha3 world info', 'Saurabh_world_info', 'JOS_world_info', 'Reynald2025_example_dataset', 'MS_202502']
['Reynald1971_world_info', 'wael__world_info', 'christian_world_info', 'LNDR_world_info', 'world_info_jack']
['world_info_jack', 'Itika_Dataset', 'nikos_world_info', 'Medryl_world_info', 'teodor_world_info']
['my_example_dataset-test', 'ag_singh_example_dataset', 'Mostafa_example_dataset', 'my_name_example_dataset', 'Arya_example_dataset']
['world_info_jack', 'saif_world_info', 'Jashoda_example_dataset', 'Henrik_world_info', 'Alq1997-AvevaNet']
['world_info_jack_JGK', 'Hariharan_world_info', 'Dipesh1994_world_info', 'world_info_jack', 'world_info_sendil']
['world_info_juju', 'Srujana_world_info', 'world_info_jader', 'EmiliesDS_v3', 'world_info_nick']
['Ravi_World_info3', 'dunham_world_info', 'Mohamed1996', 'Jorgen_world_info', 'world_info_jack']
['world_info_wwu', 'world_info_jack', 'world_info_jack', 'SampleDataset23', 'Maksym1981-1-dataset']
['my_example_dataset11', 'Ajit1992-IFSDB', 'amel_world_info_jack', 'Emilie_world_info', 'test_equip']
['abhi_example_dataset', 'elize_world_info', 'Timi_dataset1', 'Anil999_example_dataset', 'my_example_dataset']
['world_info_jack', 'world_info_jack', 'John7638', 'TestDataset_pawra', 'world_info_Ana2']
['world_info_shaheen', 'grobb_ho_dataset', 'first level', 'kiyoshi_world_info', 'saif_world_info_simple']
['JH 1st level', 'aarifov_world_info', 'world_info_mi', 'subodh_world_info', 'Jos_example_dataset']
['Shaurya_DataSet', 'Ahmad1997-ds', 'Vijaya New level', 'abhishekmaity1997_example_dataset', '1world_info_jack']
['andrew_world_info', 'afrendi_world_info', 'DP_TestDataSet2', 'NKTest123', 'akhilppujyamdataset']
['1st level', 'Vijaya level', 'mylittlepony_world_info', 'world_info_jack02', '111st level']
['wu_world_info', 'third example', 'Muddassirmm1', 'world_info_jack', 'christian_world_info']
['PTC_example_dataset', 'fj_world_info', 'joshan_world_info', 'kaminari_world_info', 'ruben_world_info']
['world_info_jack', 'world_info_jack', 'lala_level', 'my_example_dataset_abu', None]
['jd1980-AvevaNet', 'my_example_dataset', 'world_info_Sofie', 'disha_world_info_jack', 'Amin1987-ds']
['world_info_jack', 'clement_world_info', 'my_example_datasetmm', 'yahya_world_info', 'third example']
['sujit_dataset', 'Mudassir_world_info', 'Jonluca_world_info', 'world_info_jack_pavan', 'test1']
['world_info_jack_1337', 'Srujana_world_info', 'world_info_jack_1964', 'JohnS1984_world_info', '2nd level']
['jeanarnaudritouret_world_info', 'world_info_jack', 'jeanarnaudritouret_2_example_dataset', 'saif_world_info', 'BrienWorld_info']
['daniel_world_info', 'csv', 'yeshwanth_example_data', 'world_info_jack', 'Elcio19620805N_section_problems_dataset']
['world_info_jack_t', 'world_info_jack_ass', 'world_info_ricardo', 'Arpita2021-IFSDB', 'pavko_example_dataset']
['christian_world_info', '3st level', 'world_info_mi2', 'mikita_world_info_jack', 'Mostafa_world_info']
['vsa_name_example_dataset', None, 'world_info_jack', 'erick_world_info', 'Gpd2000_example_dataset']
['manssari_world_info', 'NKTest', 'vgr_world_info', 'world_info_Aliii', '_world_info']
['Mallesh1993-AvevaNet', 'world_info_test_222', 'Jorgen1990_example_dataset', 'world_info', 'ck_world_info']
['Cornelius_world_info', 'Kdunham_example_dataset', 'world_info_jack', 'emma_world_info', 'pavan1978-AvevaNet']
['Mudassir_world_info', 'name', 'Ravi_World_info3', 'Juan2001_world_info', '11st level']
['testds', 'my_example_dataset', 'daniel_world_info', 'my_example_dataset2', 'Shaurya_999']
['world_info_jack', 'Ivar2000_world_info', 'Saurabh_world_info', 'juan_world_info.232', 'my_example_dataset2']
['grrr109 test data set name', 'shawn_ts', 'world_info_jack', 'world_info_abhinav', 'Mostafa_world_info']
['Simone_world_info', 'world_info_jack', 'PM_world_info', 'Arya_World_Info', 'GCH_world_info']
['my_example_11_dataset', 'world_info_jack', 'world_info_jack', 'Abiinfojack', 'ahmad_world_info']
['wael__world_info2', 'tfrendi_world_info', 'my example', 'DeepEnd_example_dataset', 'world_info_jack']
['world_info_jack', 'FirstnameBirthyear-IFSDB', 'third example', 'world_info_amitoj', 'kailash193-Avevanet']
['world_info_jack_121', 'srujana_world_info', 'world_info_maksym1981_1', 'Aliwafasolv', 'irma_test']
['world_info_douglas', 'world_info_jack', 'world_info_fabiano', 'john_example_dataset', 'wellington1983_example_dataset']
['Akshay1993-cdm', 'world_info_abhinav', 'world_info_WillianGoulart1994', 'srujana_world_info', 'my_example_dataset']
['Yining1974-IFSDB', 'world_info_jack', 'prefix_new_example_dataset', 'my_name_example_dataset', 'EH_world_info3']
['world_info_jack', 'ruben_world_info', 'Jason1990_world_info', 'mylittlepony_example_dataset', 'world_info_halit']
['DeepEnd_world_info', 'Hasan_Hindi_example_dataset', 'sebastian_srikanth_example_dataset', 'Srmk_world_info', 'world_info_jack3']
['manolo_world_info', 'mylittlepony_world_info', 'my_example_dataset', 'my_example_dataset_x', 'world_info_christian1980']
['heydar_worl_info', 'dpg_world_info', '_world_info', 'world_info_jack', '1st level']
['Elcio19620805_section_problems_dataset', 'ariel_world_info', 'my_abhi_dataset', 'Aman1997-AvevaNet', 'rdb_example_dataset']
['_world_info', 'my_test_dataset', 'abhi_world_info', 'my_example_dataset', 'world_info_jacksonWG1994']
['world_info', 'ruben_world_info', 'world_info_jack', 'HydP2023', 'world_info_giovanna']
['2nd level', 'Ravi_example_dataset', 'my_example_dataset_par', 'pkumar105_example_dataset', 'camilla_example_dataset']
['rafael_marques_example_dataset', 'Yahya1991-AvevaNet', 'BRA_example_dataset', 'Marie_world_info', 'world_info_marissa']
['E_example_dataset', 'my_name3_example_dataset', 'christian_world_info', 'cc_my_example_dataset', 'world_info_academy']
['my_example_datasetca', '1st level_m', 'world_info_jack', 'breno_word_info', 'rdb_world_info']
['EH Dataset', 'sebastian1999_world_info', 'Henrik_world_info', 'Muhammed_Muddaththir_world_info', 'salifu83_example_dataset']
['dawei_world_info_jack', 'world_info_tb11', 'luiz1987_example_dataset', 'saif_world_info', ' my_name_example_dataset']
['name', 'world_info_jack', 'world_info_jack_hv', 'Maciej_world_info', 'world_info_jack']
['world_info_jack', 'jayme_world_info', 'world_info_jack', 'world_info_jack', 'christian_world_info']
['world_info_mfc', 'Shiva', 'irma_test', 'srmk', 'my_veryown_dataset']
['ariel_world_info', 'world_info_jack2', 'montadahar:my_example_dataset', 'mylittlepony_world_info', 'DeepEnd_world_info']
['delete_me', 'ds1', 'meher', 'johnzhu-ds', 'abhishek_rai_example_dataset']
['first level', 'my_test_ds', 'world_info_jack_daniel', 'my_work_example_dataset', 'world_info_sid']
['jujus_dataset', 'mfc_world_info', 'christian_world_info', '1st level_m', 'gabor_world_info']
['henderson_world_infov2', 'world_info_jack2', 'tachiki_example_dataset', 'Ricardo_example_dataset', 'world_info_jj']
['anj_example_dataset', 'tom_world_info', 'nick_world_info', 'my example', 'my_example_dataset']
['rena1990_world_info_jack', 'Saidatul1995_world_info', 'legit_dataset', 'Guilherme_example_dataset', 'mauricio2_example_dataset']
['world_info_jack', 'PM_world_info', 'rsinha_iom', 'Simone_world_info', 'kliang-test-ds']
['Rodrigo1997_example_dataset', 'Krystal1986-AvevaNet', None, 'muygurworld_info', 'world_info']
['ds_2', 'asha_world_info', 'Mark303-AvevaNet', '3rd_level', 'saif_world_info']
['maryam_example_dataset', 'world_info_medyo', 'my_name_vsa_example_dataset', 'Jaiprakash1988-AvevaNet.', 'second example']
['world_info_jack', 'Marcos81.5._world_info', 'PM_world_info', 'SumitB1998-IFSDB', 'LNDR_world_info_2']
['jonH_world_info', 'mojtaba_world_info', 'talal_world_info', 'name', 'jeeva_world_info']
['Mikalay1991:world_info', 'my_example_dataset_PM', 'ane_world_info', 'world_info_jack', 'ali_htx']
['Mostafa_TestDataset', 'Zacarias_example_dataset', 'JFH_world_info', 'FirstnameBirthyear-AvevaNet', 'world_info_GCH']
['Yazan_example_dataset', 'JP my_example_dataset', 'Kuni1969_example_dataset', 'Magnus1994-DS', 'Abdulmonim_World_info']
['Shaheen1985_example_dataset', 'prueba_example_dataset', 'VFMProject_ClientCompany_Roger', 'loiola_example_dataset', 'devano_example_dataset']
['Own_Create_dataset', 'phils_world_info', 'jackson_goulart2_example_dataset', 'DZ_world_info', 'Felipe_world_info']
['exerciseworld_info_jack', 'magnus_world_data', 'AM-Test', 'md_faraz', 'subham_world_info']
['irma_test', 'mx_example_dataset', 'world_info_jack_MS', 'muhammad_jib_world_info_example_dataset', 'world_info_jack']
['world_info_jack_name', 'Simone_world_info', 'world_info_jack', 'Adriano2024_101_world_info_level1', 'Raluca_world_info']
['world_info_jack', 'the_thing_example_dataset', 'world_info_afi', 'Ivar1999_world_info', 'muhammad_jibrill_world_info_example_dataset']
['MJ_WORLD', None, 'world_info_jack', 'world_info_tim', 'world_info_diego']
['world_info_GCH', 'Simon_world_info', 'vetle_example_dataset', 'Roger_example_dataset', 'PM_world_info']
['Alex1984_example_dataset', 'world_info_afrendi', 'Valdemar_world_info', 'test_dataset2', 'Compressor1992-AvevaNet']
['viniaperes_world_info', 'Rodrigo1997_world_info', 'saif_world_info', 'world_info_mark304', 'world_info_jack']
['world_info_1991_3', 'irma_test', 'world_info_andreea1', 'world_info_ole2', 'Jorgen_world_info']
['Him2_dataset', 'Marie_world_info', 'Hasan Hindi World Info', 'world_info_jack_new', 'Jader']
['my_example_dataset', '14_world_info_jack', 'world_info_jack_YDJ2025_1', 'jz_world_info', 'world_info_jack2222']
['joshan_world_info', 'Medryl_world_info', 'Alex_example_dataset', 'jeeva_world_info', 'MRosado_world_info']
['Reynald2025_world_info_jack', 'FirstnameBirthyear-AvevaNet', 'my_example_dataset', '**milton_barbosa_world_info**', 'anik_example_dataset']
['dzmitry1991_world_info', 'test', 'gcbiotec_world_info2002B', 'kiyoshi_world_info', 'Mudassir_world_info']
['muhammad_jb_example_dataset', 'andreas_world_info', '2nd level', 'Abu_world_info', 'world_info_jack']
['rsinha world info', 'second example', 'world_info_antonio', 'aman1997-IFSDB', 'ariel_world_info']
['my_example_dataset', 'mauricio-world-info-test-exercise2', 'world_info_Luiz_Cruz', 'E_world_info', 'Sumedh_Dataset']
['Ruslan_world_info', 'my_example_datasetq', '_world_info', 'Mikita1994-dataset', 'test_dataset1']
['NKTest123', 'Christian_world_info', 'grigorii_world_info', 'Function pipeline configuration', 'my_example_data_set']
['world_info_jack-1', 'erick_example_dataset', 'gokhe_example_dataset', 'Mohamed1996', 'JP_world_info']
['world_info_jack', 'Brien2World_info', 'Marie_world_info', 'Jonas_example_dataset', 'yesh4507']
['erick_world_info', 'Saketh1991_data_set', 'Dimple_example_dataset', 'NKTest1234', 'xiao_example_dataset']
['world_info_jack', 'world_info_jack_5', 'EH_world_info2', 'Henrik1999_world_info', 'Pablo1971-AvevaNet']
['ahmed_dataset', 'world_info_jack', 'world_info_kkk', 'Jader_example_dataset', 'world_info_jack']
['FirstnameBirthyear-AvevaNet', 'Joseph1999_world_info', 'Aranya_world_info', 'world_info_academy', 'changemy name']
['first level', 'lyuping_world_info_jack', 'meghna_world_info', 'third example', 'world_info_douglas']
['world_info_xyz', 'world_info', 'andersonpr1979', 'Yashwanth_data', 'Anil_world_info']
['GCH_world_info', 'world_info_jack', 'Kosuke_Miyazaki_example_dataset', 'TestDataset', 'Ravi_World_info']
['EmiliesDS_v2', 'aarne_world_info', 'Simon_example_dataset', 'Tat_world_info', 'world_info_jack']
['Jin_example_dataset', 'harry_world_info', 'my_example_dataset', 'michael_world_info', 'world_info_mfc3']
['world_info_ja', 'world_info_jack2_new', 'world_info_jack', 'Saidatul1995_world_info', 'world_info_jack']
['MS_202502', 'first level', 'DeepEnd_world_info', 'krny_world_info_jack2', 'world_info_jack']
['my_example_dataset', 'world_info_jack', 'NehaSingh_example_dataset', 'test2001_example_dataset', 'marissa_data_set']
['AndreasNordby_world_info', 'world_info_jackss', '1st lvl', 'christian_world_info', 'Aditya1999-AvevaNet']
['erik_world_info', 'muhammad_j_example_dataset', 'Lucas_example_dataset', 'Fred1_example_dataset', 'HA2023']
['samuel_example_dataset', 'sebastian1994_example_dataset', 'World info', '1st level', 'Yahya1991-IFSDB']
['DipeshYogi_example_dataset', 'Aidar_world_info', 'world_info_jack7059', 'irma_test', 'world_info_mm2']
['pax_world_info_jack', 'world_info_jack', 'Diana_test', 'Gaurav Rajurkar_world_info', 'name_sujit_example_dataset']
['aabbccdd_world_info', 'christian_world_info', 'prashant_example_dataset', 'LNDR-Data-Set', 'world_info_camilla']
['my_example_datasettestzp', 'yougiyou2000-AvevaNet', 'agnes_world_info', 'Aidar_world_info', 'Aranya5_world_info']
['world_info_jack', 'lucas-2000-world_info', 'world_info_Thilak', 'mads_world_info', 'Nate1987_world_info_jack']
['magnus_world_info', 'world_info_jack', 'Abner_example_dataset', 'T_dataset', 'world_info_jack']
['third example', 'world_info_amel', 'world_info_jack', 'world_info_jack', 'Medryl_world_info']
['world_info_jack', 'third example', 'test-ak-ds-10oct-003', 'world_info_jack_555', 'world_info_jack']
['Simon_world_info', 'world_info_jack_sid01', 'world_info_jackG', 'cp_wells', 'Isabela_world_info']
['world_info_rsandrini', 'world_info_maksym1981_3', 'world_info_jack', 'test_dataset', 'world_info_Root_Assert_Error_Test_011']
['kliang_world_info', 'Patrick1998-AvevaNet', 'world_info_sanyam', 'test_sensor_1', 'dataSet1demo']
['Aranya2_world_info', 'grigorii_world_info2', 'world_info_jack', 'JAN_world_info', 'YuiNish']
['world_info_jack', 'jz_world_info', 'amelfrendi_world_info', 'world_info_jack_005', 'delete_me']
['EZhyzneuski world_info_jack', 'world_info_jack', '1st level', 'g_ferrazzo_new_name_dataset', 'Andreea09']
['Crístian1_world_info', 'my_example_dataset', 'RSandrini_example_dataset', 'muhammad_jibril_example_dataset', 'yen_example_dataset']
['g_ferrazzo_HOE_1st_ds', None, 'world_info_jack2', 'CaioCaio', 'mduque_world_info']
['toye_world_info', 'world_info_jack', 'ds_3', 'greynoso71_world_info', 'fj_example_dataset']
['dpg2_world_info', '2nd level', 'Cornelius_example_dataset', 'world_info', 'EH_world_info4']
['johannes_world_info', 'world_info_suplentee', 'my_name_example_dataset', 'Rafli_world_info', 'daniel_world_info']
['world_info_Vipul', '3th level-gs', 'xiaoniuzhang_world_info', 'patrick1998_world_info', 'pavko_world_info']

# Searching in CDF

- Search the CDF resource types
- Filter the search results

**Code Pattern**

`client.<cdf_resource_type>.search()`

### Fuzzy Search on one field

In [31]:
client.assets.search(name="Norway",limit=5)

AssetList([<cognite.client.data_classes.assets.Asset at 0x2251b08e680>,
           <cognite.client.data_classes.assets.Asset at 0x2251b08cd90>,
           <cognite.client.data_classes.assets.Asset at 0x2251ae18670>,
           <cognite.client.data_classes.assets.Asset at 0x2251b373550>,
           <cognite.client.data_classes.assets.Asset at 0x2251b370130>])

In [32]:
client.time_series.search(name="North",limit=5)

TimeSeriesList([<cognite.client.data_classes.time_series.TimeSeries at 0x2251b3713f0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x2251b372f50>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x2251b372c20>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x2251b372380>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x2251b370460>])

In [33]:
client.files.search(name="sheet")

FileMetadataList([<cognite.client.data_classes.files.FileMetadata at 0x2251ac63fd0>,
                  <cognite.client.data_classes.files.FileMetadata at 0x2251ac63d60>,
                  <cognite.client.data_classes.files.FileMetadata at 0x2251ac62a10>,
                  <cognite.client.data_classes.files.FileMetadata at 0x2251ae18e50>,
                  <cognite.client.data_classes.files.FileMetadata at 0x2251ae17bb0>,
                  <cognite.client.data_classes.files.FileMetadata at 0x2251ae17310>,
                  <cognite.client.data_classes.files.FileMetadata at 0x2251ae17820>,
                  <cognite.client.data_classes.files.FileMetadata at 0x2251ae17a60>,
                  <cognite.client.data_classes.files.FileMetadata at 0x2251ae14340>,
                  <cognite.client.data_classes.files.FileMetadata at 0x2251ae16bf0>,
                  <cognite.client.data_classes.files.FileMetadata at 0x2251ae16da0>,
                  <cognite.client.data_classes.files.FileMetadata at 0x2251ae17430>,
                  <cognite.client.data_classes.files.FileMetadata at 0x2251aeacf70>,
                  <cognite.client.data_classes.files.FileMetadata at 0x2251aead480>,
                  <cognite.client.data_classes.files.FileMetadata at 0x225190f2200>,
                  <cognite.client.data_classes.files.FileMetadata at 0x225190f32e0>,
                  <cognite.client.data_classes.files.FileMetadata at 0x225190f2410>,
                  <cognite.client.data_classes.files.FileMetadata at 0x2251b08c130>,
                  <cognite.client.data_classes.files.FileMetadata at 0x2251b08ceb0>,
                  <cognite.client.data_classes.files.FileMetadata at 0x2251b08dc30>,
                  <cognite.client.data_classes.files.FileMetadata at 0x2251b08d960>,
                  <cognite.client.data_classes.files.FileMetadata at 0x2251b08faf0>,
                  <cognite.client.data_classes.files.FileMetadata at 0x2251ac85c90>,
                  <cognite.client.data_classes.files.FileMetadata at 0x2251ac85de0>,
                  <cognite.client.data_classes.files.FileMetadata at 0x2251ac85e70>])

Similarly for sequences and events

`client.sequences.search(name="some name")`

`client.events.search(description="some description")`

### Multi-field fuzzy search

In [34]:
client.assets.search(query="Nor",limit=5)

AssetList([<cognite.client.data_classes.assets.Asset at 0x2251ac84d00>,
           <cognite.client.data_classes.assets.Asset at 0x2251ac87be0>,
           <cognite.client.data_classes.assets.Asset at 0x2251ac85f30>,
           <cognite.client.data_classes.assets.Asset at 0x2251afb01f0>,
           <cognite.client.data_classes.assets.Asset at 0x2251b054b50>])

### Exact search on one field (e.g. name, description etc)

In [35]:
client.assets.search(filter={"name": "Canada"})

AssetList([<cognite.client.data_classes.assets.Asset at 0x2251ac62e00>,
           <cognite.client.data_classes.assets.Asset at 0x2251b3705b0>,
           <cognite.client.data_classes.assets.Asset at 0x2251b370a60>,
           <cognite.client.data_classes.assets.Asset at 0x2251b370430>,
           <cognite.client.data_classes.assets.Asset at 0x2251b3712a0>,
           <cognite.client.data_classes.assets.Asset at 0x2251b370dc0>,
           <cognite.client.data_classes.assets.Asset at 0x2251b371030>,
           <cognite.client.data_classes.assets.Asset at 0x2251b371330>,
           <cognite.client.data_classes.assets.Asset at 0x2251b373760>,
           <cognite.client.data_classes.assets.Asset at 0x2251b370580>,
           <cognite.client.data_classes.assets.Asset at 0x2251b372230>,
           <cognite.client.data_classes.assets.Asset at 0x2251b372a10>])

## get all timeseries for the above asset

In [36]:
client.time_series.search(filter={"asset_ids":[8516698919785878]})

TimeSeriesList([<cognite.client.data_classes.time_series.TimeSeries at 0x2251b371780>])

In [37]:
client.events.list()[0].type

'Volcanic activity'

In [38]:
# First get an example type to filter on
example_type = client.events.list()[0].type
# Filter the events of that type
client.events.search(filter={"type":example_type})

EventList([<cognite.client.data_classes.events.Event at 0x2251ac85cf0>,
           <cognite.client.data_classes.events.Event at 0x2251ae1f190>,
           <cognite.client.data_classes.events.Event at 0x2251ae1f8e0>,
           <cognite.client.data_classes.events.Event at 0x2251ae1f760>,
           <cognite.client.data_classes.events.Event at 0x2251ae1f820>,
           <cognite.client.data_classes.events.Event at 0x2251ae1efb0>,
           <cognite.client.data_classes.events.Event at 0x2251ae1f130>,
           <cognite.client.data_classes.events.Event at 0x2251ae1f0d0>])

### Multiple filters in search function

In [40]:
client.assets.list(data_set_external_ids=['world_info_academy'], limit=5)

AssetList([<cognite.client.data_classes.assets.Asset at 0x2251ae1fdf0>,
           <cognite.client.data_classes.assets.Asset at 0x2251ae1f5e0>,
           <cognite.client.data_classes.assets.Asset at 0x2251ae1fc40>,
           <cognite.client.data_classes.assets.Asset at 0x2251ae1d330>,
           <cognite.client.data_classes.assets.Asset at 0x2251ae1f340>])

In [41]:
client.data_sets.list()

DataSetList([<cognite.client.data_classes.data_sets.DataSet at 0x2251b055f30>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251b054ca0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251ae1f700>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251ae1f6a0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251ac87fd0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251ac85ea0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251ac85870>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251ac842b0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251ac87ca0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251afc86a0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251afca170>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251afca8f0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251afcad70>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251afc8b20>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251afc82e0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251afc9000>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251afcb3d0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251afcb100>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251afcaa70>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251afc8490>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251afcbaf0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251afca770>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251afcabf0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251b3739d0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251b371e10>])

In [42]:
client.assets.list(root=True)

AssetList([<cognite.client.data_classes.assets.Asset at 0x2251b371d80>,
           <cognite.client.data_classes.assets.Asset at 0x2251b3729e0>,
           <cognite.client.data_classes.assets.Asset at 0x2251b371900>,
           <cognite.client.data_classes.assets.Asset at 0x2251b371d20>,
           <cognite.client.data_classes.assets.Asset at 0x2251b371a20>,
           <cognite.client.data_classes.assets.Asset at 0x2251b373a30>,
           <cognite.client.data_classes.assets.Asset at 0x2251b3701c0>,
           <cognite.client.data_classes.assets.Asset at 0x2251b3726e0>,
           <cognite.client.data_classes.assets.Asset at 0x2251ac62e90>,
           <cognite.client.data_classes.assets.Asset at 0x2251ac62860>,
           <cognite.client.data_classes.assets.Asset at 0x2251ac62d40>,
           <cognite.client.data_classes.assets.Asset at 0x2251afdfcd0>,
           <cognite.client.data_classes.assets.Asset at 0x2251afdd960>,
           <cognite.client.data_classes.assets.Asset at 0x2251ac87e50>,
           <cognite.client.data_classes.assets.Asset at 0x2251ac87e20>,
           <cognite.client.data_classes.assets.Asset at 0x2251ac87cd0>,
           <cognite.client.data_classes.assets.Asset at 0x2251ac85ba0>,
           <cognite.client.data_classes.assets.Asset at 0x2251ac86050>,
           <cognite.client.data_classes.assets.Asset at 0x2251ac84550>,
           <cognite.client.data_classes.assets.Asset at 0x2251ac84a60>,
           <cognite.client.data_classes.assets.Asset at 0x2251b054d90>,
           <cognite.client.data_classes.assets.Asset at 0x2251b0550f0>,
           <cognite.client.data_classes.assets.Asset at 0x2251b0571f0>,
           <cognite.client.data_classes.assets.Asset at 0x2251b055480>,
           <cognite.client.data_classes.assets.Asset at 0x2251b0559c0>])

In [43]:
client.assets.search(name="San",filter={"parent_ids": [349354003007241]})

AssetList([<cognite.client.data_classes.assets.Asset at 0x2251ae1dba0>,
           <cognite.client.data_classes.assets.Asset at 0x2251ae1c910>,
           <cognite.client.data_classes.assets.Asset at 0x2251ae1f9a0>])

# Filter asset search using Label Filter

In [44]:
from cognite.client.data_classes import AssetFilter

In [47]:
client.assets.search(name="Norway",filter=AssetFilter(labels=LabelFilter(contains_all=["cold-countries"])),limit=5)

AssetList([<cognite.client.data_classes.assets.Asset at 0x2251ae1cbb0>,
           <cognite.client.data_classes.assets.Asset at 0x2251ae1f670>,
           <cognite.client.data_classes.assets.Asset at 0x2251ae1f5b0>,
           <cognite.client.data_classes.assets.Asset at 0x2251ae21240>,
           <cognite.client.data_classes.assets.Asset at 0x2251ae204f0>])

In [48]:
client.assets.search(name="Can",filter=AssetFilter(labels=LabelFilter(contains_all=["cold-countries"])),limit=5)

AssetList([<cognite.client.data_classes.assets.Asset at 0x2251ae205e0>,
           <cognite.client.data_classes.assets.Asset at 0x2251ae209d0>,
           <cognite.client.data_classes.assets.Asset at 0x2251ae21420>,
           <cognite.client.data_classes.assets.Asset at 0x2251ae20b80>])

# Retrieve the CDF resource types and data 
    - User only when you know the id and external_id of any component or asset

### Code Pattern
`client.<cdf_resource_type>.retrieve()`

`client.<cdf_resource_type>.retrieve_multiple()`

### Retrieve the CDF resource types

single item - using id

In [49]:
client.data_sets.list()

DataSetList([<cognite.client.data_classes.data_sets.DataSet at 0x2251ae1c250>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251ae1f3a0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251ae1f100>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251ae1f460>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251ae1fd60>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251ae1e1a0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251ae1f520>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251ae1f040>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251ae1fbe0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251ae1feb0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251ae1f250>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251ae1c340>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251ae1fc70>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251ae1ed40>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251ae1fca0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251ae1c610>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251ae1fa60>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251ae1da50>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251ae1faf0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251ae1f7c0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251ae1fd90>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251ae1f0a0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251ae1f610>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251ae1ff10>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251ae1d870>])

In [50]:
# id of dataset
client.data_sets.retrieve(id=2238694842784134)

In [51]:
client.time_series.retrieve(id=2238694842784134)

In [52]:
import datetime
# id of timeseries
client.time_series.data.retrieve(id=658605450035112, start=datetime.datetime(2018,1,1), end=datetime.datetime(2018,2,1))

single item - using external_id

In [53]:
client.data_sets.retrieve(external_id = "world_info_academy")

multiple items - using ids

In [54]:
client.data_sets.list()

DataSetList([<cognite.client.data_classes.data_sets.DataSet at 0x2251ac62bf0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251ac62f80>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251b0a08e0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251ae17400>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251ae173d0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251ae14160>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251ae17e80>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251ae14100>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251ae1df90>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251ae1fe50>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251ae1fb80>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251ae1c520>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251ae1d960>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251ae1ff70>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251b371e40>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251b373340>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251b3724d0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251b371f30>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251b370bb0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251b370eb0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251b3703d0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251b371f60>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251b373370>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251b3736a0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251b370160>])

In [55]:
client.data_sets.retrieve_multiple(ids=[39210236434027, 145208858652069])

DataSetList([<cognite.client.data_classes.data_sets.DataSet at 0x2251af46320>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251ae838e0>])

multiple items - using external_ids

In [56]:
client.data_sets.retrieve_multiple(external_ids=["test_dataset1", "test_dataset2","my_important_dataset"], ignore_unknown_ids=True)

DataSetList([<cognite.client.data_classes.data_sets.DataSet at 0x2251ae20430>,
             <cognite.client.data_classes.data_sets.DataSet at 0x2251ae203a0>])

In [57]:
from datetime import datetime
# Don't put a long datetime range, as it'll fetch all the raw datapoints, which can be huge
client.time_series.data.retrieve(external_id=['Nauru_population','Spain_population'],start=datetime(2000,1,1),end=datetime(2024,1,2))

DatapointsList([<cognite.client.data_classes.datapoints.Datapoints at 0x2251ac84490>,
                <cognite.client.data_classes.datapoints.Datapoints at 0x2251ac63040>])

### Retrieve all items related to an asset

In [58]:
# get the asset object for "Europa"
asset_obj = client.assets.retrieve(id = 349354003007241)

ConnectionError: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /48d5043c-cf70-4c49-881c-c638f5796997/oauth2/v2.0/token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002251AEAE380>: Failed to resolve 'login.microsoftonline.com' ([Errno 11001] getaddrinfo failed)"))

In [ ]:
asset_obj

Asset Subtree

In [ ]:
client.assets.retrieve_subtree(id = 349354003007241)

Children

In [ ]:
asset_obj.children()

Parent

In [ ]:
asset_obj.parent()

Events

In [ ]:
# get the asset object for "Italy"
asset_obj = client.assets.retrieve(id = 2689912833887590)

In [ ]:
asset_obj.events(limit=-1)

Timeseries

In [ ]:
# get the asset object for "Italy"
asset_obj = client.assets.retrieve(id = 2689912833887590)

In [ ]:
asset_obj.time_series()

### Retrieve data

#### Retrieve Raw Data

In [ ]:
# Don't put a long datetime range, as it'll fetch all the raw datapoints, which can be huge for Raw datapoints
client.time_series.data.retrieve(id=239507005016003, end='now')

#### Retrieve Aggregated data

In [ ]:
client.time_series.data.retrieve_dataframe(id=239507005016003,
                    end='1000w-ago',
                    aggregates=["average","sum"],
                    granularity="1h")

Retrieve latest datapoint before a particular time (last or any past time point)

In [ ]:
client.time_series.data.retrieve_latest(id=239507005016003, before="5w-ago")[0]

### Plot the data points

In [ ]:
client.time_series.data.retrieve(id=239507005016003, end='1000w-ago').to_pandas().plot()

### Download files

Download files to disk

In [ ]:
files_list = client.files.search(filter={"uploaded":True},limit=5)
files_list

In [ ]:
! mkdir files

In [ ]:
client.files.download(directory="files", id=[202614441188439, 4009508514690241])

Download a single file to a specific path

In [ ]:
client.files.download_to_path("files/test.svg", id=202614441188439)